const LOGIN_COOKIE_SHORT_SESSION_DURATION = 5;
const LOGIN_COOKIE_LONG_SESSION_DURATION = 28;
const ADMIN_COOKIE_NAME = "exchange-admin.sid";
const MEMBER_COOKIE_NAME = "exchange-member.sid";

export {
  ADMIN_COOKIE_NAME,
  LOGIN_COOKIE_LONG_SESSION_DURATION,
  LOGIN_COOKIE_SHORT_SESSION_DURATION,
  MEMBER_COOKIE_NAME,
};
